#!/bin/bash
OUTFILE=/tmp/$RANDOM.out 
ssh -q garde@localhost 2>/dev/null << EOF > $OUTFILE
audtool $1 $2
#audtool current-song
EOF
#[[ $1 = "current-song" ]] && lines=1
#tail -$lines ssh.out
tail -n +9 $OUTFILE
