#!/bin/bash
echo "Content-type: text/html"
echo
echo
playlistname=$(./audtool current-playlist-name)
pl_dir=/home/garde/.config/audacious/playlists
echo "<form action=\"nowplaying\">"
cat << EOF
<label style="font-size:2em;" for="playlist">Playlist:</label>
<select style="font-size:2em;" name="playlist" id="pl-select">"
EOF
#for i in $(seq 1 $playlistcount)
i=0
for j in $(cat $pl_dir/order)
do
   i=$((i+1))
   pl_name=$(head -1 $pl_dir/$j.audpl | sed 's|title=||g' | sed 's|%20| |g')
   selected=""
   [[ $pl_name == $playlistname ]] && selected="selected"
   echo "<option value=\"$i\" $selected> $pl_name </option>"
done
echo "</select>"
cat << EOF
 <input style="font-size:2em;" type="submit" value="Change">
</form>
EOF
